import type { Metadata } from "next";
import { Noto_Serif_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const notoserif = Noto_Serif_JP({
  variable: "--font-noto-serif"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoserif.variable} antialiased bg-[#191919] text-white`}
      >
        <div className="w-full md:w-[800px] p-3 md:m-auto md:p-0">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
